// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw2_ef.Models;

#nullable disable

namespace cw2_ef.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20250909074023_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("cw2_ef.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrzej Sapkowski",
                            PublishedDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wiedźmin: Ostatnie życzenie"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.K. Rowling",
                            PublishedDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hobbit, czyli tam i z powrotem"
                        });
                });

            modelBuilder.Entity("cw2_ef.Models.Editor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Editors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Wookkk, Kraków 31-161",
                            Name = "Appress"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Wookkk, Kraków 31-161",
                            Name = "Trrrrr"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ul. Wookkk, Kraków 31-161",
                            Name = "Rainbow"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ul. Zygmunta, Kraków 31-161",
                            Name = "Feryk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
